export type ReceteMalzeme = {
  malzeme: string;
  gram: number;
};

export type Recete = {
  urun: string;
  malzemeler: ReceteMalzeme[];
};

export const receteler: Recete[] = [
  {
    urun: "Thales",
    malzemeler: [
      { malzeme: "Baget Ekmek", gram: 180 },
      { malzeme: "Beyaz Peynir", gram: 55 },
      { malzeme: "Krem Peynir", gram: 20 },
      { malzeme: "Kaşar Peyniri", gram: 27 },
      { malzeme: "Zeytin Ezmesi", gram: 20 },
      { malzeme: "Domates", gram: 60 },
      { malzeme: "Salatalık", gram: 50 },
      { malzeme: "Zeytinyağı", gram: 5 },
      { malzeme: "Kuru Kekik", gram: 1 },
      { malzeme: "Kuru Nane", gram: 1 },
    ],
  },
  {
    urun: "Pisagor",
    malzemeler: [
      { malzeme: "Baget Ekmek", gram: 180 },
      { malzeme: "Iceberg", gram: 15 },
      { malzeme: "Roka", gram: 15 },
      { malzeme: "Domates", gram: 60 },
      { malzeme: "Mısır", gram: 25 },
      { malzeme: "Köz Biber", gram: 45 },
      { malzeme: "Beyaz Peynir", gram: 55 },
      { malzeme: "Zeytinyağı", gram: 5 },
      { malzeme: "Kuru Kekik", gram: 1 },
      { malzeme: "Kuru Nane", gram: 1 },
    ],
  },
  {
    urun: "Heredot",
    malzemeler: [
      { malzeme: "Baget Ekmek", gram: 180 },
      { malzeme: "Iceberg", gram: 15 },
      { malzeme: "Roka", gram: 15 },
      { malzeme: "Domates", gram: 60 },
      { malzeme: "Hellim Peyniri", gram: 52 },
      { malzeme: "Köz Biber", gram: 45 },
      { malzeme: "Zeytinyağı", gram: 5 },
      { malzeme: "Kuru Kekik", gram: 1 },
      { malzeme: "Kuru Nane", gram: 1 },
    ],
  },
  {
    urun: "Demokritos",
    malzemeler: [
      { malzeme: "Baget Ekmek", gram: 180 },
      { malzeme: "Domates", gram: 60 },
      { malzeme: "Lutenitsa Sos", gram: 20 },
      { malzeme: "Roka", gram: 15 },
      { malzeme: "Tulum Peyniri", gram: 45 },
      { malzeme: "Ceviz", gram: 15 },
      { malzeme: "Mısır", gram: 25 },
      { malzeme: "Zeytinyağı", gram: 5 },
      { malzeme: "Kuru Fesleğen", gram: 1 },
    ],
  },
  {
    urun: "Öklid",
    malzemeler: [
      { malzeme: "Baget Ekmek", gram: 180 },
      { malzeme: "Amerikan Salatası", gram: 60 },
      { malzeme: "Domates", gram: 60 },
      { malzeme: "Yeşil Biber", gram: 30 },
      { malzeme: "Kaşar Peyniri", gram: 27 },
      { malzeme: "Yumurta", gram: 50 },
      { malzeme: "Zeytinyağı", gram: 5 },
      { malzeme: "Kuru Kekik", gram: 1 },
      { malzeme: "Kuru Nane", gram: 1 },
    ],
  },
  {
    urun: "Erasmus",
    malzemeler: [
      { malzeme: "Baget Ekmek", gram: 180 },
      { malzeme: "Hindi Salam", gram: 40 },
      { malzeme: "Kaşar Peyniri", gram: 27 },
      { malzeme: "Domates", gram: 60 },
      { malzeme: "Iceberg", gram: 15 },
      { malzeme: "BBQ Sos", gram: 15 },
      { malzeme: "Mayonez", gram: 15 },
    ],
  },
  {
    urun: "Diyojen",
    malzemeler: [
      { malzeme: "Baget Ekmek", gram: 180 },
      { malzeme: "Krem Peynir", gram: 20 },
      { malzeme: "Iceberg", gram: 15 },
      { malzeme: "Hindi Füme", gram: 40 },
      { malzeme: "Köz Biber", gram: 45 },
      { malzeme: "Domates", gram: 60 },
      { malzeme: "Turşu", gram: 30 },
      { malzeme: "Mayonez", gram: 15 },
    ],
  },
  {
    urun: "Aristo",
    malzemeler: [
      { malzeme: "Baget Ekmek", gram: 180 },
      { malzeme: "Iceberg", gram: 15 },
      { malzeme: "Domates", gram: 60 },
      { malzeme: "Dana Jambon", gram: 40 },
      { malzeme: "Dana Salam", gram: 40 },
      { malzeme: "Kaşar Peyniri", gram: 27 },
      { malzeme: "BBQ Sos", gram: 15 },
      { malzeme: "Mayonez", gram: 15 },
    ],
  },
  {
    urun: "Spinoza",
    malzemeler: [
      { malzeme: "Baget Ekmek", gram: 180 },
      { malzeme: "Iceberg", gram: 15 },
      { malzeme: "Domates", gram: 60 },
      { malzeme: "Dana Jambon", gram: 40 },
      { malzeme: "Rozbif", gram: 40 },
      { malzeme: "Kaşar Peyniri", gram: 27 },
      { malzeme: "BBQ Sos", gram: 15 },
      { malzeme: "Mayonez", gram: 15 },
    ],
  },
  {
    urun: "Sokrates",
    malzemeler: [
      { malzeme: "Baget Ekmek", gram: 180 },
      { malzeme: "Krem Peynir", gram: 20 },
      { malzeme: "Iceberg", gram: 15 },
      { malzeme: "Domates", gram: 60 },
      { malzeme: "Ton Balığı", gram: 80 },
      { malzeme: "Mısır", gram: 25 },
      { malzeme: "Mayonez", gram: 15 },
    ],
  },
  {
    urun: "Kopernik",
    malzemeler: [
      { malzeme: "Baget Ekmek", gram: 180 },
      { malzeme: "Amerikan Salatası", gram: 60 },
      { malzeme: "Kaşar Peyniri", gram: 27 },
      { malzeme: "Ton Balığı", gram: 80 },
      { malzeme: "Iceberg", gram: 15 },
      { malzeme: "Ketçap", gram: 15 },
    ],
  },
  {
    urun: "Platon",
    malzemeler: [
      { malzeme: "Baget Ekmek", gram: 180 },
      { malzeme: "Krem Peynir", gram: 20 },
      { malzeme: "Köz Biber", gram: 45 },
      { malzeme: "Roka", gram: 15 },
      { malzeme: "Kaşar Peyniri", gram: 27 },
      { malzeme: "Kuzu Cotto", gram: 40 },
      { malzeme: "Trüf Mayonez", gram: 15 },
    ],
  },
  {
    urun: "Heraklitos",
    malzemeler: [
      { malzeme: "Baget Ekmek", gram: 180 },
      { malzeme: "Nutella", gram: 30 },
      { malzeme: "Muz", gram: 60 },
      { malzeme: "Kaşar Peyniri", gram: 27 },
      { malzeme: "Ceviz", gram: 15 },
      { malzeme: "Bal", gram: 15 },
      { malzeme: "Tereyağı", gram: 10 },
    ],
  },
  {
    urun: "Ton Balıklı Salata",
    malzemeler: [
      { malzeme: "Iceberg", gram: 140 },
      { malzeme: "Domates", gram: 125 },
      { malzeme: "Salatalık", gram: 75 },
      { malzeme: "Turşu", gram: 25 },
      { malzeme: "Köz Biber", gram: 40 },
      { malzeme: "Mısır", gram: 25 },
      { malzeme: "Ton Balığı", gram: 80 },
      { malzeme: "Zeytinyağı", gram: 10 },
    ],
  },
  {
    urun: "Tulum Peynirli & Cevizli Salata",
    malzemeler: [
      { malzeme: "Iceberg", gram: 140 },
      { malzeme: "Domates", gram: 125 },
      { malzeme: "Salatalık", gram: 75 },
      { malzeme: "Turşu", gram: 25 },
      { malzeme: "Köz Biber", gram: 40 },
      { malzeme: "Roka", gram: 15 },
      { malzeme: "Mısır", gram: 25 },
      { malzeme: "Tulum Peyniri", gram: 45 },
      { malzeme: "Ceviz", gram: 15 },
      { malzeme: "Nar Ekşisi", gram: 10 },
      { malzeme: "Zeytinyağı", gram: 10 },
    ],
  },
  {
    urun: "Hellim Salata",
    malzemeler: [
      { malzeme: "Iceberg", gram: 140 },
      { malzeme: "Domates", gram: 125 },
      { malzeme: "Salatalık", gram: 75 },
      { malzeme: "Köz Biber", gram: 40 },
      { malzeme: "Roka", gram: 15 },
      { malzeme: "Mısır", gram: 25 },
      { malzeme: "Hellim Peyniri", gram: 52 },
      { malzeme: "Dilimli Siyah Zeytin", gram: 25 },
      { malzeme: "Limon Suyu", gram: 10 },
      { malzeme: "Zeytinyağı", gram: 10 },
    ],
  },
  {
    urun: "Akdeniz Salata",
    malzemeler: [
      { malzeme: "Iceberg", gram: 140 },
      { malzeme: "Domates", gram: 125 },
      { malzeme: "Salatalık", gram: 75 },
      { malzeme: "Köz Biber", gram: 40 },
      { malzeme: "Roka", gram: 15 },
      { malzeme: "Mısır", gram: 25 },
      { malzeme: "Beyaz Peynir", gram: 55 },
      { malzeme: "Limon Suyu", gram: 10 },
      { malzeme: "Zeytinyağı", gram: 10 },
    ],
  },
  {
    urun: "Aristo Club Salata",
    malzemeler: [
      { malzeme: "Iceberg", gram: 140 },
      { malzeme: "Domates", gram: 125 },
      { malzeme: "Salatalık", gram: 75 },
      { malzeme: "Köz Biber", gram: 40 },
      { malzeme: "Mısır", gram: 25 },
      { malzeme: "Hindi Füme", gram: 40 },
      { malzeme: "Dilimli Siyah Zeytin", gram: 25 },
      { malzeme: "Limon Suyu", gram: 10 },
      { malzeme: "Zeytinyağı", gram: 10 },
    ],
  },
];